[test-groups.ssh-integration]
max-threads = 4

[test-groups.ssh-integration-windows]
max-threads = 2

[test-groups.docker-integration]
max-threads = 2

[profile.default]
fail-fast = false
leak-timeout = { period = "100ms", result = "fail" }
status-level = "fail"
final-status-level = "leak"

[[profile.default.overrides]]
filter = 'binary_id(distant-ssh::lib)'
platform = 'cfg(target_os = "windows")'
test-group = 'ssh-integration-windows'

[[profile.default.overrides]]
filter = 'binary_id(distant-ssh::lib)'
test-group = 'ssh-integration'

[[profile.default.overrides]]
filter = 'binary_id(distant-docker::lib)'
test-group = 'docker-integration'

[profile.ci]
retries = { backoff = "exponential", count = 4, delay = "1s", max-delay = "16s", jitter = true }
slow-timeout = { period = "60s", terminate-after = 3 }
