[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-rdynamic"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-rdynamic"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-rdynamic"]
